Add NaufalPrakoso in Contributors
lombok-android-developer/kotlin-everywhere-mataram-web pull request #35
Opened 2019-10-06 01:47 UTC by naufalprakoso

2019-10-06 06:56 UTC, ha-yi requested changes

2019-10-06 06:56 UTC, ha-yi commented on resources/templates/mustache/NaufalPrakoso_CvResume.hbs
> +<!-- Portfolio Section
tolong remove semua komentar...

2019-10-07 01:05 UTC, naufalprakoso commented on resources/templates/mustache/NaufalPrakoso_CvResume.hbs
> +<!-- Portfolio Section
Okay

2019-10-10 16:42 UTC, naufalprakoso commented
Apakah sudah ok mas?

2019-10-11 16:44 UTC, anwar907 approved these changes

2019-10-11 16:45 UTC, ariaji25 approved these changes

2019-10-11 16:48 UTC, ha-yi approved these changes

2019-10-11 16:48 UTC, merged