Add AgungSaputra as contributor
lombok-android-developer/kotlin-everywhere-mataram-web pull request #44
Opened 2019-10-13 18:23 UTC by agungsptr

Add AgungSaputra as contributor, I fixed the file that duplicate and not used. Thanks for review my pull request.

2019-10-14 05:24 UTC, ha-yi commented
sudah terlalu banyak bootstrap css dan jquery js,, pake yg sudah ada saja..

2019-10-15 01:18 UTC, ha-yi requested changes

2019-10-15 01:18 UTC, ha-yi commented on resources/res/agungsptr/js/jquery/jquery.min.js
> +/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/license */
gunakan jQuery JS yg sudah ada.

2019-10-15 01:19 UTC, ha-yi commented on resources/res/agungsptr/js/jquery/jquery.min.js
> +/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/license */
berlaku juga untuk selain file ini,,, yg sudah ada jangan di add lagi.

2019-10-16 03:12 UTC, agungsptr commented on resources/res/agungsptr/js/jquery/jquery.min.js
> +/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/license */
siap bang sy rubah lagi

2019-10-16 03:12 UTC, closed without merging