Add Ricky CV
lombok-android-developer/kotlin-everywhere-mataram-web pull request #45
Opened 2019-10-13 22:43 UTC by rickyanwar

2019-10-14 01:23 UTC, rickyanwar commented
Clean Code for calling Resources
1.Make Repository for Global Resources (/resources/res/globalRes) for fixing :

- use the same version of Bootstrap

- use the same version of JQuery (if applicable)

- use remote version of all CSS/JS do not use local, remove any redudant CSS and JS files.

2019-10-15 01:22 UTC, ha-yi commented
mention issue number nya ya...

2019-10-15 11:28 UTC, rickyanwar commented
Cuman ngapus resource yang sama mas,terus saya buatin resource global,cuman punya anwar aja ngak saya rubah

2019-10-20 22:21 UTC, anwar907 approved these changes

2019-10-21 01:27 UTC, ha-yi commented
Masih ada yg ga jalan js nya, terutama yg template aji dan nauval.

2019-10-21 01:28 UTC, ha-yi requested changes

2019-10-21 01:28 UTC, ha-yi commented on resources/res/globalRes/css/AriajiStyle.css
> +/*
di bagian JS nya template Aji ini masih ga works....
di console ada 20 error pas nge run dari PR ini... mintol d cek ulang ya...

2019-11-07 07:12 UTC, closed without merging