Kontribusi Kotlin Everywhere Mataram Web
lombok-android-developer/kotlin-everywhere-mataram-web pull request #54
Opened 2019-10-22 01:34 UTC by lukmancyb

Menambahkan class kontribusi baru, acc min ;)

2019-10-22 13:48 UTC, ha-yi requested changes

2019-10-22 13:48 UTC, ha-yi commented on src/ContributorHelper.kt
> +            LukmanHakim.initialize(this)
masih conflic di sini.... silahkan d resolve dulu...

2019-10-23 07:34 UTC, lukmancyb commented on src/ContributorHelper.kt
> +            LukmanHakim.initialize(this)
Sudah bang hayii

2019-10-24 01:40 UTC, ha-yi requested changes

2019-10-24 01:40 UTC, ha-yi commented on src/ContributorHelper.kt
> -            AgungSaputra.initialize(this)
ini kok nge hapus ya??mustinya cuma nambah...

2019-10-24 05:54 UTC, lukmancyb commented on src/ContributorHelper.kt
> -            AgungSaputra.initialize(this)
Oh iya bang sorry :(

2019-10-25 11:56 UTC, merged